name: Tests

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r dev-requirements.txt
    - name: Build the collection
      run: |
        python3 -m ansible-galaxy collection build
    - name: Test the collection
      run: |
        python3 -m ansible-galaxy install syntropynet-syntropy-*.tar.gz -p .collections
        cd .collections/ansible_collections/syntropynet/syntropy
        python3 -m ansible-test sanity --python ${{ matrix.python }}
        python3 -m ansible-test units --python ${{ matrix.python }}
