name: Tests

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip setuptools
        pip3 install -r dev-requirements.txt
    - name: Build the collection
      run: |
        python3 j2.py galaxy.yml.j2 -p version 1.2.3-alpha > galaxy.yml
        ansible-galaxy collection build
    - name: Test the collection
      run: |
        ansible-galaxy collection install syntropynet-syntropy-1.2.3-alpha.tar.gz -p .-collections
        cd .-collections/ansible_collections/syntropynet/syntropy
        ansible-test sanity --python ${{ matrix.python }}
        ansible-test units --python ${{ matrix.python }}
